### ISSUE TITLE
Doesn't work on Windows 8

### ISSUE THREAD

**Issue by jmkristian** [mfncooper/paracon#5]
Although python is available on Windows 8, paracon doesn't work:
```
PS C:\Users\John\Desktop\paracon> python .\paracon_1.1.0.pyz
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\__main__.py", line 3, in <module>
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\paracon.py", line 1473, in run
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\paracon.py", line 1015, in run
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\urwid\event_loop\main_loop.py", line 337, in run
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\urwid\event_loop\main_loop.py", line 430, in _run
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\urwid\event_loop\main_loop.py", line 389, in start
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\urwid\display\common.py", line 1029, in start
  File "C:\Users\John\Desktop\paracon\paracon_1.1.0.pyz\urwid\display\_win32_raw_display.py", line 99, in _start
RuntimeError: ConsoleMode set failed for output. Err: 0
←[?1049hPS C:\Users\John\Desktop\paracon>
```
I guess it never will, since this type of TUI isn't supported by older versions of Windows' Command Prompt or PowerShell.

Please note this dependency up front, ideally in the [README](https://github.com/mfncooper/paracon/blob/main/README.md) and/or the documentation [front page](https://paracon.readthedocs.io/en/latest/). That will save people from going to the trouble of installing Python to no avail.

**Comment by mfncooper** [comment]
That would be an unfortunate limitation of Urwid, the TUI library on which Paracon is built. At this time, Urwid does not document the limitation either, so I was unaware of it, and I don't have Windows 8 to test against.

Given that extended support for Windows 8.1 ended almost a year and a half ago, I'm not overly concerned about this, but I can add a note somewhere. I've filed a similar request against Urwid to document it as part of their Windows limitations.

**Comment by devinhedge** [comment]
FWIW, as of [January 10, 2023, Microsoft no longer provides security updates or technical support for Windows 8.1,](https://www.microsoft.com/en-us/windows/end-of-support) so I wouldn't expect newer versions of Python to be as backwards compatible at some point. Checking the Python website, v3.8.x still supports Windows 8.x.
